/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.view.manager;

import com.edusys.dao.EmployeeDAO;
import com.edusys.helper.AppStatus;
import com.edusys.helper.DialogHelper;
import com.edusys.helper.ShareHelper;
import com.edusys.view.dialog.LoadingDialog;
import com.edusys.view.dialog.LoginDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        
        initComponents();
        init();
//        openLoading();
//        openLogin();

    }

    public void init() {
        this.setIconImage(ShareHelper.APP_ICON);
        this.setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        AppStatus.OPEN_CONTROLLER.initApp(this);
        startTime();

        if (!AppStatus.isFirstStart()) {
           // openLoading();
        //    openLogin();
            AppStatus.USER = new EmployeeDAO().findById("ThinhLP");
            AppStatus.STATUS =1;
        }

        if (AppStatus.USER != null) {
            txtLore.setText(AppStatus.USER.isLore() == true ? "Quản lý" : "Nhân viên");
            txtUsername.setText(AppStatus.USER.getName());
        }
    }

    public void startTime() {
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblSystemTime.setText(format.format(new Date()));
            }
        }).start();

    }

    public void openLoading() {
        new LoadingDialog(this, true).setVisible(true);
    }

    public void openLogin() {
        new LoginDialog(this, true).setVisible(true);
    }
    
    
    public void openCourseManager(){
        AppStatus.OPEN_CONTROLLER.openCourseManager();
    }
    
//    public void openEmployeeManager(){
//       AppStatus.OPEN_CONTROLLER.openEmployeeManager();
//    }
//    
//    public void openEmployeeManager(String maNV){
//       AppStatus.OPEN_CONTROLLER.openEmployeeManager(maNV);
//    }
//    
//    public void openLearnerManager(){
//        //new LearnerManager().setVisible(true);
//        ///this.setEnabled(false);
//        AppStatus.OPEN_CONTROLLER.openLearnerManager();
//    }
//    
    public void openMajorManager(){
        AppStatus.OPEN_CONTROLLER.openMajorManager();
    }
    
    public void openStatiscalManager(int index){
         AppStatus.OPEN_CONTROLLER.openStatiscalManager(index);
        
    }
    
  

    public void logoff() {

        AppStatus.logoff();
        this.dispose();

        openLogin();
        new HomePage().setVisible(true);

    }

    void exit() {
        if (DialogHelper.confirm(this, "Bạn thực sự muốn kết thúc?")) {
            System.exit(0);
        }
    }

    public void resetUI() {
        txtLore.setText(AppStatus.USER.isLore() == true ? "Quản lý" : "Nhân viên");
        txtUsername.setText(AppStatus.USER.getName());
    }
    
//    public void unableMainFrame(boolean is){
//        this.setEnabled(is);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnLearner = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnMajor = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JLabel();
        txtLore = new javax.swing.JLabel();
        statusBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSystemTime = new javax.swing.JLabel();
        lblMainLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        btnLogin = new javax.swing.JMenuItem();
        btnLogoff = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnChangePass = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnExit2 = new javax.swing.JMenuItem();
        mnuManager = new javax.swing.JMenu();
        btnLearner2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnMajor2 = new javax.swing.JMenuItem();
        btnCourse2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnEmployee = new javax.swing.JMenuItem();
        mnuStatistical = new javax.swing.JMenu();
        btnLearnerInYear = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnCoursePoint = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnPointMajor = new javax.swing.JMenuItem();
        btnRevenue = new javax.swing.JMenuItem();
        mnuSupport = new javax.swing.JMenu();
        btnGuide2 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Stop.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setInheritsPopupMenu(true);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLearner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/User.png"))); // NOI18N
        btnLearner.setText("Người học");
        btnLearner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLearner.setInheritsPopupMenu(true);
        btnLearner.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLearner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnerActionPerformed(evt);
            }
        });

        btnCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/List.png"))); // NOI18N
        btnCourse.setText("Khóa học");
        btnCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourse.setInheritsPopupMenu(true);
        btnCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        btnMajor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Bar chart.png"))); // NOI18N
        btnMajor.setText("Chuyên đề");
        btnMajor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMajor.setInheritsPopupMenu(true);
        btnMajor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMajorActionPerformed(evt);
            }
        });

        btnGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Online.png"))); // NOI18N
        btnGuide.setText("Hướng dẫn");
        btnGuide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuide.setInheritsPopupMenu(true);
        btnGuide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuideActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Open door.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setInheritsPopupMenu(true);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("Admin");
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });

        txtLore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLore.setForeground(new java.awt.Color(255, 255, 255));
        txtLore.setText("Vai Tro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLearner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLore, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuide))
            .addComponent(jSeparator8)
            .addComponent(jSeparator9)
            .addComponent(btnLogout)
            .addComponent(btnMajor)
            .addComponent(btnCourse)
            .addComponent(btnLearner)
            .addComponent(btnExit)
            .addComponent(txtLore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        statusBar.setBackground(new java.awt.Color(204, 204, 204));
        statusBar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/info.png"))); // NOI18N

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setText("Hệ thống quản lý đào tạo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/clock.png"))); // NOI18N

        lblSystemTime.setText("Time");

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSystemTime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSystemTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/logoFpt.png"))); // NOI18N

        mnuSystem.setText("Hệ thống");
        mnuSystem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuSystem.setMargin(new java.awt.Insets(0, 0, 0, 10));

        btnLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/login.png"))); // NOI18N
        btnLogin.setText("Đăng nhập");
        mnuSystem.add(btnLogin);

        btnLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Open door.png"))); // NOI18N
        btnLogoff.setText("Đăng xuất");
        mnuSystem.add(btnLogoff);
        mnuSystem.add(jSeparator1);

        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Refresh.png"))); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        mnuSystem.add(btnChangePass);
        mnuSystem.add(jSeparator2);

        btnExit2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        btnExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Delete.png"))); // NOI18N
        btnExit2.setText("Thoát");
        mnuSystem.add(btnExit2);

        jMenuBar1.add(mnuSystem);

        mnuManager.setText("Quản lý");
        mnuManager.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuManager.setMargin(new java.awt.Insets(0, 0, 0, 10));

        btnLearner2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/User.png"))); // NOI18N
        btnLearner2.setText("Người học");
        btnLearner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearner2ActionPerformed(evt);
            }
        });
        mnuManager.add(btnLearner2);
        mnuManager.add(jSeparator3);

        btnMajor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Bar chart.png"))); // NOI18N
        btnMajor2.setText("Chuyên đề");
        btnMajor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMajor2ActionPerformed(evt);
            }
        });
        mnuManager.add(btnMajor2);

        btnCourse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/List.png"))); // NOI18N
        btnCourse2.setText("Khóa học");
        btnCourse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourse2ActionPerformed(evt);
            }
        });
        mnuManager.add(btnCourse2);
        mnuManager.add(jSeparator4);

        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Boy.png"))); // NOI18N
        btnEmployee.setText("Nhân viên");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        mnuManager.add(btnEmployee);

        jMenuBar1.add(mnuManager);

        mnuStatistical.setText("Thống kê");
        mnuStatistical.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuStatistical.setMargin(new java.awt.Insets(0, 0, 0, 10));

        btnLearnerInYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/User group.png"))); // NOI18N
        btnLearnerInYear.setText("Người học theo năm");
        btnLearnerInYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnerInYearActionPerformed(evt);
            }
        });
        mnuStatistical.add(btnLearnerInYear);
        mnuStatistical.add(jSeparator5);

        btnCoursePoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Lists.png"))); // NOI18N
        btnCoursePoint.setText("Bảng điểm khóa");
        btnCoursePoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursePointActionPerformed(evt);
            }
        });
        mnuStatistical.add(btnCoursePoint);
        mnuStatistical.add(jSeparator6);

        btnPointMajor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Numbered list.png"))); // NOI18N
        btnPointMajor.setText("Bảng điểm từng chuyen de");
        btnPointMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointMajorActionPerformed(evt);
            }
        });
        mnuStatistical.add(btnPointMajor);

        btnRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Statistics.png"))); // NOI18N
        btnRevenue.setText("Doanh thu từng chuyên đề");
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });
        mnuStatistical.add(btnRevenue);

        jMenuBar1.add(mnuStatistical);

        mnuSupport.setText("Trợ giúp");
        mnuSupport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnuSupport.setMargin(new java.awt.Insets(0, 0, 0, 10));

        btnGuide2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        btnGuide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/Online.png"))); // NOI18N
        btnGuide2.setText("Hướng dẫn sử dụng");
        btnGuide2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuide2ActionPerformed(evt);
            }
        });
        mnuSupport.add(btnGuide2);
        mnuSupport.add(jSeparator7);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/assets/info.png"))); // NOI18N
        btnAbout.setText("Giới thiệu sản phẩm");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        mnuSupport.add(btnAbout);

        jMenuBar1.add(mnuSupport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMainLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLearner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearner2ActionPerformed
      //openLearnerManager();
    }//GEN-LAST:event_btnLearner2ActionPerformed

    private void btnCourse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourse2ActionPerformed
        openCourseManager();
    }//GEN-LAST:event_btnCourse2ActionPerformed

    private void btnLearnerInYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnerInYearActionPerformed
        openStatiscalManager(0); // learner in year
    }//GEN-LAST:event_btnLearnerInYearActionPerformed

    private void btnPointMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointMajorActionPerformed
         openStatiscalManager(2); // point of major
    }//GEN-LAST:event_btnPointMajorActionPerformed

    private void btnGuide2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuide2ActionPerformed
        
    }//GEN-LAST:event_btnGuide2ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLearnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnerActionPerformed
        //  openLearnerManager();
    }//GEN-LAST:event_btnLearnerActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        openCourseManager();
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajorActionPerformed
        openMajorManager();
    }//GEN-LAST:event_btnMajorActionPerformed

    private void btnGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuideActionPerformed
         
    }//GEN-LAST:event_btnGuideActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logoff();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnCoursePointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursePointActionPerformed
        openStatiscalManager(1); // point of course
    }//GEN-LAST:event_btnCoursePointActionPerformed

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        openStatiscalManager(3); // revenue
    }//GEN-LAST:event_btnRevenueActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
      //  openEmployeeManager();
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
    //  openEmployeeManager(AppStatus.USER.getEmpID());
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btnMajor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajor2ActionPerformed
       openMajorManager();
    }//GEN-LAST:event_btnMajor2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnChangePass;
    private javax.swing.JButton btnCourse;
    private javax.swing.JMenuItem btnCourse2;
    private javax.swing.JMenuItem btnCoursePoint;
    private javax.swing.JMenuItem btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JMenuItem btnExit2;
    private javax.swing.JButton btnGuide;
    private javax.swing.JMenuItem btnGuide2;
    private javax.swing.JButton btnLearner;
    private javax.swing.JMenuItem btnLearner2;
    private javax.swing.JMenuItem btnLearnerInYear;
    private javax.swing.JMenuItem btnLogin;
    private javax.swing.JMenuItem btnLogoff;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMajor;
    private javax.swing.JMenuItem btnMajor2;
    private javax.swing.JMenuItem btnPointMajor;
    private javax.swing.JMenuItem btnRevenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblMainLogo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSystemTime;
    private javax.swing.JMenu mnuManager;
    private javax.swing.JMenu mnuStatistical;
    private javax.swing.JMenu mnuSupport;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel txtLore;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
