/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.view.manager;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ADMIN
 */
public class ManagerForm extends javax.swing.JPanel {

    private LearnerManage learnerManager;
    private MajorManager majorManger;
    private CourseManager2 courseManager;
    private EmployeeManager employeeManager;
    private MigLayout layout;
    
       static class SUB_MENU_MANAGER {

        static int LEARNER_MANAGER = 1;
        static int MAJOR_MANAGER = 3;
        static int EMMPLOYEE_MANAGER = 0;
        static int COURSE_MANAGER = 2;
    }

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        initComponents();

        setOpaque(false);
        setLayout(new BorderLayout());
        setBorder(new EmptyBorder(10, 20, 10, 20));
        tabPane.setOpaque(false);

        layout = new MigLayout("fill", "0[]0[100%, fill]0", "0[fill, top]0");
        setLayout(layout);
        
    

        courseManager = new CourseManager2();
        add(tabPane, "h 70!, wrap");
        add(courseManager, "w 100%, h 100%");

    }
    
    public void tabSelected(int index){
        if (index == SUB_MENU_MANAGER.LEARNER_MANAGER){
            learnerManager = new LearnerManage();
            showForm(learnerManager);
        }else if (index == SUB_MENU_MANAGER.MAJOR_MANAGER){
            majorManger = new MajorManager();
            showForm(majorManger);
        }else if (index == SUB_MENU_MANAGER.EMMPLOYEE_MANAGER){
            employeeManager = new EmployeeManager();
            showForm(employeeManager);
        }else if (index == SUB_MENU_MANAGER.COURSE_MANAGER){
            courseManager = new CourseManager2();
            showForm(courseManager);
        }
    }
            
            
     public void showForm(Component form) {
        remove(getComponentCount()-1);
        add(form, "w 100%, h 100%");
        repaint();
        revalidate();
    }        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JPanel();
        btnLearenerManger = new com.ui.swing.component.Tab();
        jLabel1 = new javax.swing.JLabel();
        btnEmployeeManager = new com.ui.swing.component.Tab();
        jLabel5 = new javax.swing.JLabel();
        btnCourseManager = new com.ui.swing.component.Tab();
        jLabel6 = new javax.swing.JLabel();
        btnMajorManager = new com.ui.swing.component.Tab();
        jLabel7 = new javax.swing.JLabel();

        tabPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPaneMousePressed(evt);
            }
        });

        btnLearenerManger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLearenerMangerMouseClicked(evt);
            }
        });
        btnLearenerManger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý người học");
        btnLearenerManger.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        btnEmployeeManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeeManagerMouseClicked(evt);
            }
        });
        btnEmployeeManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quản lý nhân viên");
        btnEmployeeManager.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        btnCourseManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseManagerMouseClicked(evt);
            }
        });
        btnCourseManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quản lý khóa học");
        btnCourseManager.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        btnMajorManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMajorManagerMouseClicked(evt);
            }
        });
        btnMajorManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quản lý chuyên đề");
        btnMajorManager.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        javax.swing.GroupLayout tabPaneLayout = new javax.swing.GroupLayout(tabPane);
        tabPane.setLayout(tabPaneLayout);
        tabPaneLayout.setHorizontalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnLearenerManger, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnEmployeeManager, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnCourseManager, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnMajorManager, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(710, Short.MAX_VALUE))
        );
        tabPaneLayout.setVerticalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLearenerManger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployeeManager, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseManager, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMajorManager, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 780, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMousePressed
       
        btnMajorManager.clear();
    }//GEN-LAST:event_tabPaneMousePressed

    private void tabPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMouseClicked
        
    }//GEN-LAST:event_tabPaneMouseClicked

    private void btnLearenerMangerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLearenerMangerMouseClicked
        
        
        btnLearenerManger.clear();
        btnEmployeeManager.clear();
        btnCourseManager.clear();
        btnMajorManager.clear();
        
        btnLearenerManger.click();
        tabSelected(SUB_MENU_MANAGER.LEARNER_MANAGER);
    }//GEN-LAST:event_btnLearenerMangerMouseClicked

    private void btnEmployeeManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeManagerMouseClicked
       
        btnLearenerManger.clear();
        btnEmployeeManager.clear();
        btnCourseManager.clear();
        btnMajorManager.clear();
        
        btnEmployeeManager.click();
           tabSelected(SUB_MENU_MANAGER.EMMPLOYEE_MANAGER);
    }//GEN-LAST:event_btnEmployeeManagerMouseClicked

    private void btnCourseManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseManagerMouseClicked
       
        
        btnLearenerManger.clear();
        btnEmployeeManager.clear();
        btnCourseManager.clear();
        btnMajorManager.clear();
        
        btnCourseManager.click();
           tabSelected(SUB_MENU_MANAGER.COURSE_MANAGER);
    }//GEN-LAST:event_btnCourseManagerMouseClicked

    private void btnMajorManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMajorManagerMouseClicked
    
        
        btnLearenerManger.clear();
        btnEmployeeManager.clear();
        btnCourseManager.clear();
        btnMajorManager.clear();
        
        btnMajorManager.click();
           tabSelected(SUB_MENU_MANAGER.MAJOR_MANAGER);
    }//GEN-LAST:event_btnMajorManagerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.component.Tab btnCourseManager;
    private com.ui.swing.component.Tab btnEmployeeManager;
    private com.ui.swing.component.Tab btnLearenerManger;
    private com.ui.swing.component.Tab btnMajorManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel tabPane;
    // End of variables declaration//GEN-END:variables
}
